# docker-compose.yml
version: "3.9"
services:
  redis:
    image: redis:7.2-alpine        # невеликий імідж
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
